# mkdocs.yml
site_name: Docs
site_url: https://ramuskay.github.io/doc/
theme:
  name: mkdocs
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
